page_gen-dirs: true # uncomment, if you prefer to generate named folders
page_gen:
  - data: 'members'
    template: 'profile'
    name: 'full_name'
    dir: 'people'
    
  - data: 'pets'
    template: 'pet'
    name: 'pet_name'
    dir: 'pets'
